require:
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  NewCops: enable

Lint/MissingCopEnableDirective:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

# Layout/ArrayAlignment:
#   Enabled: true
#   EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Exclude:
  - db/migrate/**/*
