# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.3"

gem "rails", "~> 7.0.3", ">= 7.0.3.1"

gem "bcrypt", "~> 3.1"
gem "bootsnap", require: false
gem "clerk-sdk-ruby", require: "clerk"
gem "dry-struct", "~> 1.6"
gem "faraday", "~> 1.4"
gem "graphql"
gem "jbuilder"
gem "jwt"
gem "pagy", "~> 6.0"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "pundit"
gem "rack-cors"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 5.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development do
  gem "dockerfile-rails", ">= 1.2"
  gem "graphiql-rails"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
end
