---
version: "3.7"

services:
  proxy:
    image: nginx:1.23.2-alpine
    volumes:
      - ./services/proxy/config/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  api:
    image: devopsfaith/krakend:watch
    volumes:
      - ./services/api/config/krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.dev.json"]

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=tasks_dev,tasks_test
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data
      - ./script/dev/pg-init:/docker-entrypoint-initdb.d

volumes:
  pg_data:
