root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tasks"
bin = "./tasks"
full_bin = "./tasks"
include_ext = ["go", "tpl", "tmpl", "html", "mustache", "hbs", "pug"]
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_regex = ["_test.go"]
exclude_unchanged = true
delay = 1000 # ms
stop_on_error = true
log = "air.log"
send_interrupt = true

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
