# fly.toml file generated for rems-tasks on 2022-10-28T14:19:48-07:00

app = "rems-tasks"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  DB_USER = "rems_tasks"
  DB_HOST = "top2.nearest.of.rems-db.internal"
  TASKS_BIND = "[::]"
  TASKS_PORT = "4002"
  TASKS_DATABASE = "rems_tasks"
  TASKS_USE_IPV6 = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4002
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  # [[services.ports]]
  #   force_https = true
  #   handlers = ["http"]
  #   port = 80
  #
  # [[services.ports]]
  #   handlers = ["tls", "http"]
  #   port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
