development:
  dialect: postgres
  database: properties_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: properties_test
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

production:
  url: {{envOr "PROPERTIES_DB_URL" "postgres://postgres:postgres@127.0.0.1:5432/properties_production"}}
