development:
  dialect: postgres
  database: properties_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: properties_test
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: properties_production
  user: {{envOr "PROPERTIES_DB_USER" "postgres"}}
  password: {{envOr "PROPERTIES_DB_PASS" "postgres"}}
  host: {{envOr "PROPERTIES_DB_HOST" "127.0.0.1"}}
  pool: 5
