default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: core_development
  url: postgres://postgres:postgres@localhost

test:
  <<: *default
  database: core_test
  url: postgres://postgres:postgres@localhost

production:
  <<: *default
  database: todo_production
  url: <%= ENV["DB_URL"] %>
