name: Deploy
on:
  push:
    branches:
      - main
      - deploy
jobs:
  deploy:
    name: Deploy REMS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy web application
        run: |
          curl -sf https://gobinaries.com/tj/robo | sh
          robo prod deploy/gh/app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
