name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy REMS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install dependencies
        run: curl -sf https://gobinaries.com/tj/robo | sh

      - name: Deploy admin service
        run: robo prod deploy/admin
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy web application
        run: robo prod deploy/app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
