env:
  summary: setup development environment
  command: |
    yes | cp .env.development .env
    direnv allow

setup:
  summary: run setup tasks
  command: script/dev/setup.sh

up:
  summary: start development services
  command: script/dev/up.sh

down:
  summary: stop development services
  command: |
    docker compose down
    overmind quit

db/reset:
  summary: reset local databases
  command: |
    pushd services/properties
    soda drop -e development
    soda drop -e test
    soda create -e development
    soda create -e test
    popd

db/migrate:
  summary: apply database migrations
  command: |
    pushd services/properties
    soda migrate up
    popd
