env:
  summary: setup development environment
  command: |
    yes | cp .env.development .env
    direnv allow

setup:
  summary: run setup tasks
  command: script/dev/setup.sh

up:
  summary: start development services
  command: |
    docker compose up -d
    overmind start

down:
  summary: stop development services
  command: |
    docker compose down
    overmind quit
