prepare:
  summary: prepare the application environment
  command: script/prod/prepare.sh

deploy:
  summary: deploy application
  command: script/prod/deploy.sh

deploy/all:
  summary: deploy all components
  command: |
    robo -c {{ .robo.file }} deploy/api
    robo -c {{ .robo.file }} deploy/admin
    robo -c {{ .robo.file }} deploy/app

deploy/api:
  summary: deploy the API gateway
  command: |
    cd services/api
    flyctl deploy

deploy/app:
  summary: deploy the web app
  command: |
    cd web/app
    flyctl deploy

deploy/admin:
  summary: deploy the admin service
  command: |
    cd services/admin
    flyctl deploy

deploy/core:
  summary: deploy the core service
  command: |
    cd services/core
    flyctl deploy --build-secret clerk_publishable_key=$(cat ./secrets/clerk_publishable_key)

deploy/properties:
  summary: deploy the properties service
  command: |
    cd services/properties
    flyctl deploy
