prepare:
  summary: prepare the application environment
  command: script/prod/prepare.sh

deploy:
  summary: deploy application
  command: script/prod/deploy.sh

deploy/all:
  summary: deploy all components
  command: |
    robo -c {{ .robo.file }} deploy/api
    robo -c {{ .robo.file }} deploy/app

deploy/api:
  summary: deploy the API gateway
  command: |
    flyctl deploy \
      -a rems-api \
      --local-only \
      --dockerfile docker/Dockerfile.api

deploy/app:
  summary: deploy the web app
  command: |
    flyctl deploy \
      -a rems-app \
      --local-only \
      --dockerfile docker/Dockerfile.app

deploy/core:
  summary: deploy the core backend
  command: |
    cd services/core
    flyctl deploy

deploy/gh/app:
  summary: deploy the web app from a Github action
  command: |
    flyctl deploy \
      -a rems-app \
      --remote-only \
      --dockerfile docker/Dockerfile.app
